<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <ShotLensVersionWithPrefix>$([System.IO.File]::ReadAllText('$(MSBuildThisFileDirectory)VERSION').Trim())</ShotLensVersionWithPrefix>
    <ShotLensVersion>$([System.Text.RegularExpressions.Regex]::Replace('$(ShotLensVersionWithPrefix)', '^v', ''))</ShotLensVersion>
    <Version>$(ShotLensVersion)</Version>
    <InformationalVersion>$(ShotLensVersionWithPrefix)</InformationalVersion>
    <AssemblyVersion>$(ShotLensVersion).0</AssemblyVersion>
    <FileVersion>$(ShotLensVersion).0</FileVersion>
    <Company>Qingcheng</Company>
    <Product>ShotLens</Product>
    <Copyright>MIT</Copyright>
  </PropertyGroup>
</Project>
